name: micropack_ui_kit
description: A UI Kit package for Micropack.
version: 0.2.0
homepage: https://github.com/ajianaz/micropack-ui-kit.git

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  extended_image: ">=8.1.1 <11.0.0"
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2

  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  flutter_switch: ^0.3.2
  gap: ^3.0.1
  get_it: ^9.2.0
  google_fonts: ">=6.1.0 <8.0.0"
  nil: ^1.1.1
  skeletonizer: ">=0.8.0 <3.0.0"
  # lottie: ^2.7.0
  # tap_debouncer: ^2.2.0

dev_dependencies:
  flutter_lints: ">=2.0.0 <7.0.0"
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  very_good_analysis: ">=8.0.0 <11.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/
  #   - assets/images/

flutter_gen:
  output: lib/src/core/assets/gen/
  integrations:
    flutter_svg: true
    lottie: true
