name: micropack_ui_kit
description: A UI Kit package for Micropack.
version: 0.3.0
homepage: https://github.com/ajianaz/micropack-ui-kit.git

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  extended_image: ^10.0.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2

  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.0.9
  flutter_switch: ^0.3.2
  gap: ^3.0.1
  get_it: ^9.2.0
  google_fonts: ^6.1.0
  nil: ^1.1.1
  shared_preferences: ^2.5.3
  skeletonizer: ^1.4.3
  carousel_slider_x: ^6.0.7
  flutter_slidable: ^4.0.2
  # lottie: ^2.7.0
  # tap_debouncer: ^2.2.0

dev_dependencies:
  flutter_lints: '>=2.0.0 <6.0.0'
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  very_good_analysis: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  #   - assets/images/

flutter_gen:
  output: lib/src/core/assets/gen/
  integrations:
    flutter_svg: true
    lottie: true
